#ifndef REPLIES_HPP
#define REPLIES_HPP

// Successful replies (001-099)
#define RPL_WELCOME         001
#define RPL_YOURHOST        002
#define RPL_CREATED         003
#define RPL_MYINFO          004

// Error replies (400-599)
#define ERR_NOSUCHNICK      401
#define ERR_NOSUCHCHANNEL   403
#define ERR_CANNOTSENDTOCHAN 404
#define ERR_NORECIPIENT     411
#define ERR_NOTEXTTOSEND    412
#define ERR_UNKNOWNCOMMAND  421
#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEOUSNICKNAME 432
#define ERR_NICKNAMEINUSE   433
#define ERR_NOTREGISTERED   451
#define ERR_NEEDMOREPARAMS  461
#define ERR_ALREADYREGISTERED 462
#define ERR_PASSWDMISMATCH  464

#endif
